### ISSUE TITLE
[Chrome] [Intro] - Incorrect responsive behavior of the item "Discover the training offer "

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/eroforestiero-landing#10]
**Step by step:**
1- I reach Ero Forestiero site with a Desktop device

3- I set the screen to responsive mode

**Expected result:**
I expect to see the correct responsive "Discover the training offer" item behaviour

**Actual result:**
Incorrect responsive behavior of the item "Discover the training offer "

**Comment by andrea-artuso** [comment]
I've fixed the issue and now it should work properly. The code is inside the dev branch
