### ISSUE TITLE
[Chrome] [Courses] - Wrong base course dimensions

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/eroforestiero-landing#2]
**Step by step:**
1- I reach Ero Forestiero site with a Desktop device

2- I scroll to courses section

**Expected result:**
I expect to see the base course card with the same dimensions as the cards of the other courses

**Actual result:**
Wrong base course dimensions

![bug-courses](https://user-images.githubusercontent.com/35035423/133921881-6858a799-6443-4e4e-b3ba-424e1516c389.png)

![offerta-formativa](https://user-images.githubusercontent.com/35035423/133921884-02f3c4f5-4a09-44e7-971c-0b3fefdfc76b.png)

**Comment by andrea-artuso** [comment]
I've fixed this issue. I created a bugfix branch called "bugfix/courses-section" where I've uploaded the code. I've merged it in the dev branch.
