### ISSUE TITLE
[Chrome] [Testimonials] - Testimonial card graphic bug starting from the following resolution: 1270px x 700px

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/eroforestiero-landing#3]
Step by step:
1- I reach Ero Forestiero site with a Desktop device

2- I scroll to testimonials section

3- I set the screen resolution to: 1270px x 700px

Expected result:
I expect to see the testimonials card in tablet mode and without graphic bugs

Actual result:
Testimonial card graphic bug starting from the following resolution: 1270px x 700px

![testimonianze-card](https://user-images.githubusercontent.com/35035423/133921982-8ebbf6c5-67f5-44ac-982c-b201e123d34a.png)

**Comment by andrea-artuso** [comment]
I've fixed this issue. I created a bugfix branch called "bugfix/testimonials-section" where I've uploaded the code. I've merged it in the dev branch.

**Comment by ludovicobesana** [comment]
@andrea-artuso I saw the fix but there is still a graphic problem related to media queries

I leave you a video:
https://www.loom.com/share/3e186f465107432aa91f66b3d509a0d5

**Comment by ludovicobesana** [comment]
@andrea-artuso I confirm  the bug is not more present 🤙
